### PR TITLE
Added CurlNoSsl Adapter

### PR DESCRIPTION
**Pull request by dsentker**
I've added an Adapter which does not require an SSL certificate. This is very useful for development environments and it facilitates beginners to work with this project.

### CODE REVIEW

**Comment by MrCrankHank** [comment]
I'm curious, do you have a fints test server? So far i'm building my application with my own bank account. But a test api would be very helpful.

However, i think adding a adapter which basically kills security is not a good idea. You can get free valid ssl certs from let's encrypt or wosign. If you don't that, you still can create your own and import it.

Just my 2 cents.

**Comment by dsentker** [comment]
I know that an SSL-less request is not state-of-the-art, but as i wrote, it would be helpful for quick tests. I recommend to add a note "Not for use in production" or something else.

No, i do not have an fints test server, i've used the library with my own bank account, too. I suggest to add mock objects to emulate FinTS responses.

**Comment by mschindler83** [comment]
Hi @dsentker,
Thanks for contributing.

In my opinion we could take this PR.
Correct me if I'm wrong but I think we do not kill security because the bank servers only accept SSL connections for the PIN/TAN method.

For other methods like raw HBCI (which are not implemented at the moment) we could then use this adapter. 

On the other hand - to be honest - I see no current use case for the no ssl adapter.
@dsentker can you explain your use case? Maybe it gets clearer then.

+1 for the Mock objects.

**Comment by MrCrankHank** [comment]
Your right, bank servers only accept ssl/tls connections. But the adapter still supports ssl, just without certificate validation, doesn't it? At least if I read the curl php documentation right.

**Comment by dsentker** [comment]
Hi @mschindler83, thank you for your statement. A common use-case is given when a developer is trying to access the finTS endpoint without a valid cert.
If i run a script without a cert file, i get the following exception:

```
Fatal error: Uncaught Fhp\Adapter\Exception\CurlException: Failed connection to https://banking-dkb.s-fints-pt-dkb.de/fints30 in [path]\vendor\mschindler83\fints-hbci-php\lib\Fhp\Adapter\Curl.php on line 80

Fhp\Adapter\Exception\CurlException: Failed connection to https://banking-dkb.s-fints-pt-dkb.de/fints30 in [path]\vendor\mschindler83\fints-hbci-php\lib\Fhp\Adapter\Curl.php on line 80

Call Stack:
    0.0004     362928   1. {main}() [path]\index.php:0
    0.0076     531744   2. Fhp\FinTs->getSEPAAccounts() [path]\index.php:29
    0.0083     575952   3. Fhp\Dialog\Dialog->syncDialog() [path]\vendor\mschindler83\fints-hbci-php\lib\Fhp\FinTs.php:126
    0.0204     705520   4. Fhp\Dialog\Dialog->sendMessage() [path]\vendor\mschindler83\fints-hbci-php\lib\Fhp\Dialog\Dialog.php:325

```

An unexperienced developer would think it involves a CURL error, without, however, to think of an SSL certificate issue.

**Comment by MrCrankHank** [comment]
I don't want to be a naysayer, but to me this really sounds like a bad idea. 

Even in development you should not send your login data via an unvalidated ssl connection.

The real fix here, is to document this error and to tell unexperienced developers, how to fix certificate validations (which in most likely already works out of box).

**Comment by mschindler83** [comment]
> But the adapter still supports ssl, just without certificate validation, doesn't it?

Yes you're completely right @MrCrankHank.
And +1 for better error handling on curl exceptions.

@dsentker you really shouldn't access the finTS endpoint without a valid cert.
If you have to, then you're free to use your own curl adapter implementation to match your needs.
But for now I think its better to not take the NoSSL adapter into the repository.

Anyways... thanks for your effort. At least we know now that we have to improve the error handling further :)

**Pull request closed without merging**
